#!/bin/bash
###################################
# configuration file for deployment
###################################

# where 'alphonse' will be deployed
ALPHONSE_BIN_DIR=/usr/local/sbin/

# where 'alphonse' data will be store (phone books, whitelist, blacklist, ...)
ALPHONSE_DATA_DIR=/var/lib/alphonse/


# where 'alphonse' will log
ALPHONSE_LOG_FILE=/var/log/alphonse

#==================================
# systemd service
#==================================
# do you want 'alphonse' in systemd ? 'yes' or 'no'
ALPHONSE_SERVICE=yes
ALPHONSE_SERVICE_DIR=/etc/systemd/system/

#==================================
# web interface
#==================================
# do you want 'alphonse' web interface ? 'yes' or 'no'
ALPHONSE_WEB=no
ALPHONSE_WWW_DIR=/var/www/html/
ALPHONSE_CGI_BIN_DIR=/usr/lib/cgi-bin/
