//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisfactoryModeler.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatisfactoryModeler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20px_Miner_Mk_1 {
            get {
                object obj = ResourceManager.GetObject("_20px_Miner_Mk_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Configuration&gt;
        ///  &lt;ItemTypes&gt;
        ///    &lt;ItemType SS=&quot;100&quot; SV=&quot;8&quot;     Id=&quot;Bauxite&quot;          Lbl=&quot;Bauxite&quot;       /&gt;
        ///    &lt;ItemType SS=&quot;100&quot; SV=&quot;7&quot;     Id=&quot;CateriumOre&quot;      Lbl=&quot;Caterium Ore&quot;  /&gt;
        ///    &lt;ItemType SS=&quot;100&quot; SV=&quot;3&quot;     Id=&quot;Coal&quot;             Lbl=&quot;Coal&quot;          /&gt;
        ///    &lt;ItemType SS=&quot;100&quot; SV=&quot;3&quot;     Id=&quot;CopperOre&quot;        Lbl=&quot;Copper Ore&quot;    /&gt;
        ///    &lt;ItemType SS=&quot;100&quot; SV=&quot;1&quot;     Id=&quot;IronOre&quot;          Lbl=&quot;Iron Ore&quot;      /&gt;
        ///    &lt;ItemType SS=&quot;100&quot; SV=&quot;2&quot;     Id=&quot;L [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Miner_Mk_3 {
            get {
                object obj = ResourceManager.GetObject("Miner_Mk_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
