//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyrimUserSwitch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyrimUserSwitch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skus.conf.
        /// </summary>
        internal static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlMap_Custom.txt.
        /// </summary>
        internal static string ControlMap_CustomTxt {
            get {
                return ResourceManager.GetString("ControlMap_CustomTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam/SteamApps/Common/Skyrim.
        /// </summary>
        internal static string DefaultSkyrimRelativePath {
            get {
                return ResourceManager.GetString("DefaultSkyrimRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Games/Skyrim.
        /// </summary>
        internal static string DefaultSkyrimUserRelativePath {
            get {
                return ResourceManager.GetString("DefaultSkyrimUserRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory &apos;{0}&apos;..
        /// </summary>
        internal static string FMessageFailedToCreateDirectory {
            get {
                return ResourceManager.GetString("FMessageFailedToCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save user config file &apos;{0}&apos;..
        /// </summary>
        internal static string FMessageFailedToSaveUserFile {
            get {
                return ResourceManager.GetString("FMessageFailedToSaveUserFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start &apos;{0}&apos;..
        /// </summary>
        internal static string FMessageFailedToStartSkyrimLauncher {
            get {
                return ResourceManager.GetString("FMessageFailedToStartSkyrimLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyrim folder is not valide. &apos;{0}&apos; does not contain {1} and {2}..
        /// </summary>
        internal static string FMessageInvalideSkyrimFolder {
            get {
                return ResourceManager.GetString("FMessageInvalideSkyrimFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; is already used..
        /// </summary>
        internal static string FMessageNameAlreadyUsed {
            get {
                return ResourceManager.GetString("FMessageNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove user &apos;{0}&apos;..
        /// </summary>
        internal static string FMessageRemoveFailed {
            get {
                return ResourceManager.GetString("FMessageRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves folder do not exist ({0})..
        /// </summary>
        internal static string FMessageSavesFolderDoNotExist {
            get {
                return ResourceManager.GetString("FMessageSavesFolderDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyrim folder do not exist &apos;{0}&apos;..
        /// </summary>
        internal static string FMessageSkyrimFolderDoNotExist {
            get {
                return ResourceManager.GetString("FMessageSkyrimFolderDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyrim user folder do not exist &apos;{0}&apos;..
        /// </summary>
        internal static string FMessageSkyrimUserFolderDoNotExist {
            get {
                return ResourceManager.GetString("FMessageSkyrimUserFolderDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos; ? You saves will not destroyed..
        /// </summary>
        internal static string FMessageSuppression {
            get {
                return ResourceManager.GetString("FMessageSuppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the user :.
        /// </summary>
        internal static string MessageUserName {
            get {
                return ResourceManager.GetString("MessageUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves.
        /// </summary>
        internal static string SavesRelativePath {
            get {
                return ResourceManager.GetString("SavesRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyrim.ini.
        /// </summary>
        internal static string SkyrimIni {
            get {
                return ResourceManager.GetString("SkyrimIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyrimLauncher.exe.
        /// </summary>
        internal static string SkyrimLauncherExe {
            get {
                return ResourceManager.GetString("SkyrimLauncherExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyrimPrefs.ini.
        /// </summary>
        internal static string SkyrimPrefsIni {
            get {
                return ResourceManager.GetString("SkyrimPrefsIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESV.exe.
        /// </summary>
        internal static string TESVExe {
            get {
                return ResourceManager.GetString("TESVExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression.
        /// </summary>
        internal static string TitleSuppression {
            get {
                return ResourceManager.GetString("TitleSuppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string TitleUserName {
            get {
                return ResourceManager.GetString("TitleUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnnknowGuy {
            get {
                object obj = ResourceManager.GetObject("UnnknowGuy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.skus.conf.
        /// </summary>
        internal static string UserFileName {
            get {
                return ResourceManager.GetString("UserFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon UserSwitch {
            get {
                object obj = ResourceManager.GetObject("UserSwitch", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
