# syntax=docker/dockerfile:1

ARG NODE_VERSION=22.18.0

# === Stage 1: Dev - Angular Application
FROM node:${NODE_VERSION}-alpine AS dev

ENV NODE_ENV=development

WORKDIR /app

COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

EXPOSE 4200

CMD ["npm", "start", "--", "--host=0.0.0.0"]
